### ISSUE TITLE
fonts.googleapis.com retuan 127.0.0.1

### ISSUE THREAD

**Issue by qoli** [gentlyxu/anti-AD#1]
建議使用並非 127.0.0.1 的地址作為拒絕地址。
如果本地機器會作為的服務器的話，那麼將會導致整個過程很慢（等待服務器超時）。

另外，建議移除 fonts.googleapis.com 條目，雖然我不知道你怎麼做觸發了這個問題。

```
$ ping fonts.googleapis.com
PING googleadapis.l.google.com (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.046 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.053 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.063 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.045 ms
^C
--- googleadapis.l.google.com ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.045/0.052/0.063/0.007 ms
```

**Comment by gentlyxu** [comment]
查了一下，在easylist中存在该记录，虽然不知道怎么加进去的。

```bash
user@host:~/anti-AD$ grep -F 'googleadapis.l.google.com' *
adblock-for-dnsmasq.conf:address=/.googleadapis.l.google.com/127.0.0.1
easylistchina+easylist.txt:||googleadapis.l.google.com^$third-party
```
现在加入白名单了

**Comment by gentlyxu** [comment]
查了一下，在easylist中存在该记录,脚本解析并正确添加了
<img width="515" alt="1" src="https://user-images.githubusercontent.com/1243610/62833918-6c43f080-bc78-11e9-8b79-e0edd6469a67.png">

现在已将该域名加入白名单

**Comment by JunShine** [comment]
问下，如果不用 127.0.0.1 作为拒绝地址，那一般应该用什么地址呢？为什么用这个会导致过程慢？

**Comment by qoli** [comment]
> 问下，如果不用 127.0.0.1 作为拒绝地址，那一般应该用什么地址呢？为什么用这个会导致过程慢？

可以選擇一些不存在的 ip 地址，如果本地是開發機的話，在 127 上面搭建了服務器，就要等 404 錯誤了。所以會變慢。一般人不在本地建立服務器的話，就沒事。
