### ISSUE TITLE
Cloudflare issue

### ISSUE THREAD

**Issue by Redback813** [gentlyxu/anti-AD#2]
I have never seen a cloudflare url start with "." at the beginning, I say this is a mistake
example:
"address=/.d"3asksgk2foh5m.cloudfront.net/127.0.0.1
"address=/d"3asksgk2foh5m.cloudfront.net/127.0.0.1

address=/.d3asksgk2foh5m.cloudfront.net/127.0.0.1
address=/.dkm6b5q0h53z4.cloudfront.net/127.0.0.1
address=/.d1wi563t0137vz.cloudfront.net/127.0.0.1
address=/.d2q52i8yx3j68p.cloudfront.net/127.0.0.1
address=/.d39hdzmeufnl50.cloudfront.net/127.0.0.1
address=/d1grtyyel8f1mh.cloudfront.net/127.0.0.1
address=/d31qbv1cthcecs.cloudfront.net/127.0.0.1

**Comment by gentlyxu** [comment]
thank you for your feedback. it's fixed now.
