### ISSUE TITLE
列表存在某 URL 被過濾導致 Google Play 無法正常更新 App

### ISSUE THREAD

**Issue by qoli** [gentlyxu/anti-AD#3]
在應用此 adblock 后，Google Play 無法更新任何軟件。

在移除此 adblock 后，Google Play 正常更新。

我目前未能從 Logcat 確定是哪條 URL 被過濾導致。

懷疑和 https://play.googleapis.com/play/log?format=raw&proto_v2=true 此地址有關係。

部分資料參考：
https://forum.adguard.com/index.php?threads/resolved-google-play-service.10771/

**Comment by gentlyxu** [comment]
感谢反馈。手头没有Android手机，你提供的play.googleapis.com也并不在屏蔽列表中，参考[这篇帖子](https://support.opendns.com/hc/en-us/community/posts/220036447-block-google-play-)，gvt1.com着实被屏蔽，现在已经加到白名单，你帮忙看看问题是否解决。

**Comment by qoli** [comment]
應該沒問題了，謝謝。
