### ISSUE TITLE
可以在gitee上把这个项目也同步建一个吗？

### ISSUE THREAD

**Issue by xyzcheese** [gentlyxu/anti-AD#4]
如题。github下载速度有时候真是慢啊，明明adblock-for-dnsmasq.conf就1M大一点，我的路由器更新dnsmasqs规则下载时经常失败，感觉很无奈啊。

要是能把这个项目也同步放到国内的gitee上，感觉就OK了。至少速度没问题了。

**Comment by gentlyxu** [comment]
https://anti-ad.coding.net/p/main/d/main/git/raw/master/adblock-for-dnsmasq.conf

试试这个地址，速度如何。国内的代码托管环境各种不确定，我也没有了解anti-AD项目是否会动了某个投资人的奶酪，而遭到删库，所以，如果速度有改善，你完全可以自己拉取本项目的代码，定期进行镜像，这不需要额外的授权，欢迎扩散随意使用

**Comment by gentlyxu** [comment]
OK

**Comment by rufengsuixing** [comment]
https://cdn.jsdelivr.net
可以考虑

**Comment by gentlyxu** [comment]
好主意
